[ui]
listen = "0.0.0.0:9090"
secret = "admin"
serve_path = "/jffs/anywhere/ui"

[common]
cache_dir = "/jffs/anywhere"

# [dns]
# dns server used for direct out, default setted
# support doh but pub doh server has rate limit, recommend set custom doh server
# default only set last two udp servers
# direct = ["https://doh.pub/dns-query", "https://dns.alidns.com/dns-query", "https://doh.360.cn/dns-query", "223.5.5.5", "114.114.114.114"]
# dns server ip used for others, default setted
# remote = ["8.8.8.8", "1.1.1.1"]
# default setted, Warn: set false can close it, but will cause dns leak
# fakeip = "198.18.0.0/15"

[[inbounds]]
type = "tun" #only support in linux with ip & iptables, run as root.
tag = "tun-in"
# name = "tun0"
# addr = "10.0.0.1/24"
# mtu = 1500
# Auto set iptables for tun, advance user can set false and manage all ip route & rules.
# auto_route = true
# Auto set iptables for dns, no effect when aute_route=false
# auto_hijack = true
# WAN ifaces are monitored dynamically and only get `from <wan_ip>` rules.
# No effect when auto_hijack=false, linux desktop no need this
monitor_wan_ifaces = ["ppp0"]
# LAN ifaces get startup `from <lan_ip>` / `to <lan_subnet>` bypass rules and DNAT mangle marks. 
# No effect when auto_hijack=false, linux desktop no need this
bypass_lan_ifaces = ["br0", "eth0"]
# All local query direct out, default true for router, linux desktop must set false
# local_direct = true

[[inbounds]]
type = "socks5"
listen = "127.0.0.1:1080"

[[outbounds]]
type = "anytls"
tag = "A"
server = "001.top:423"
password = "15e023sae"
sni = "fafeg.qq.com"
# fp = true
# idle_session_check_interval = 60
# idle_session_timeout = 180
# min_idle_session = 2

[[outbounds]]
type = "shadowsocks"
tag = "S"
server = "V.z.t:3"
method = "2022-blake3-aes-128-gcm"
password = "jgjhkhkkhnknknk==:gjhbkhkhkkhii=="
plugin = "obfs-local"
plugin_opts = "obfs=http;obfs-host=os.i.a.com"

[[outbounds]]
type = "mless"
tag = "CF1"
server = "1.5.8.5:2087"
password = ""
sni = "h.c.c"
# fp = true (default)

[outbounds.transport]
type = "ws"

[outbounds.transport.ws]
path = "/"
headers = { Host = "h.c.c" }

# [outbounds.xmux]
# pool_size = 5

[[outbounds]]
type = "vless"
tag = "CF2"
server = "11.11.1.11:2083"
password = "xxxxx"
sni = "h.p.dev"

[outbounds.transport]
type = "ws"

[outbounds.transport.ws]
path = "/"
headers = { Host = "h.p.dev" }

[[outbounds]]
type = "ssh"
tag = "mac"
cmd = "ssh -o ExitOnForwardFailure=yes -K 10 -i /jffs/anywhere/id_dropbear -N -L {PORT}:127.0.0.1:6518 192.168.1.30"
server = "127.0.0.1:{PORT}"

[[outbounds]]
type = "urltest"
tag = "auto"
outbounds = ["A", "S", "CF1", "CF2"]
# outbounds = ["mac"]
#interval = 600
#url = "www.google.com"

[[rules]]
# protocol examples: "both:1232" "tcp:123,1132" "udp:123,2222"
protocol = "stun"  # both:3748,3749
outbound = "none" # drop the traffic

[[rules]]
# some software use other ports such as Xunlei, recommend set direct mode in ui when download.
protocol = "bittorrent" # tcp:6881,6889 && udp:6881,
outbound = "direct"

[[rules]]
# NTP
protocol = "udp:123"
outbound = "direct"

[[rules]]
# mDNS
protocol = "udp:5353"
outbound = "direct"

[[rules]]
# NetBIOS
protocol = "udp:137,139"
outbound = "direct"

[[rules]]
# DHCP
protocol = "udp:67,68"
outbound = "direct"

[[rules]]
domain_suffix = [
    "lmstudio.ai",
    "rust-lang.org",
    "microsoft.com",
    "npmjs.org",
    "apple.com",
    "cdn-apple.com",
    "synologyupdate.com",
    "synology.com",
    "hf-mirror.com",
    "xethub.hf.co",
    "pythonhosted.org",
    "pytorch.org",
    "pypi.org",
    "wireshark.org"
]
outbound = "direct"

[[rules]]
geo_url = "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/private.srs"
# update_interval = "3d"
# on router is none, linux desktop set direct
outbound = "none"

[[rules]]
geo_url = "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/cn.srs"
outbound = "direct"

[[rules]]
geo_url = "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-games@cn.srs"
outbound = "direct"

[[rules]]
geo_url = "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/cn.srs"
outbound = "direct"

[[rules]]
geo_url = "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ads-all.srs"
outbound = "none"

[[rules]]
geo_url = "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/geolocation-!cn.srs"
outbound = "auto"

[[rules]]
outbound = "auto"